### ISSUE TITLE
Problem to create a new tile based on 'rawhtml'

### ISSUE THREAD

**Issue by rristow** [plone/plone.app.mosaic#232]
I'm tryinng to create a new tile. The tile is inherited from rawhtml (plone.app.standardtiles.rawhtml). Everything worked perfect, I can add my tile and the text editor works.
If try to edit an existing document however, the editor doesn’t shows up.
The reason for this behavior is a “hardcoded” check for the tile name in the js:

```
/home/vagrant/www.fhnw.ch/parts/packages/plone/app/mosaic/browser/static/js/mosaic.tile.js[80]
>>      if(tiletype === 'plone.app.standardtiles.rawhtml'){

```
The js must to verify not the name, but the type of the tile registered in the registry.xml
```
    <value key="tile_type">textapp</value>
or
    <value key="tile_type">text</value>

```
===
As a ‘workaround’ it was possible to ‘overwrite’ the original code from ‘rawhtml’ with my-code. This is probably also not ok, because I was expecting ‘conflict’ in the configure.zcml (two tiles registered with the same name)

===

CODE:

```
###  Configure.zcml
  <plone:tile
        name="fhnw.tiles.wi_020_accordeon"
<!-- workaournd        name="plone.app.standardtiles.rawhtml" -->
        title="WI_020_Accordeon"
        description=""
        add_permission="cmf.ModifyPortalContent"
        class=".tiles.AccordeonTile"
        for="*"
        permission="zope2.View"
        schema=".tiles.IAccordeonTile"
        />

### Tiles.py
class IAccordeonTile(IRawHTMLTile):
    pass
class AccordeonTile(RawHTMLTile, HandlebarsMixin):
    pass

### registry.xml
  <records prefix="plone.app.mosaic.app_tiles.wi_020_accordeon"
           interface="plone.app.mosaic.interfaces.ITile">
<!-- workaround:    <value key="name">plone.app.standardtiles.rawhtml</value> -->
    <value key="name">fhnw.tiles.wi_020_accordeon</value>
    <value key="tile_type">textapp</value>
    <value key="read_only">False</value>
    <value key="settings">False</value>
    <value key="favorite">False</value>
    <value key="rich_text">true</value>
  </records>

```

**Comment by vangheem** [comment]
I'm not sure what is going on here; although, this might be the more about how the editor completely borks when a tile is missing or incorrectly configured. At the very least, we need to make mosaic more resilient when it can't handle a tile configuration.

**Comment by rristow** [comment]
This is true, but in this case is not really about a incorrect configuration.
Another way to say is:  it's not possible to create a new tile (type) with the same behaviour as 'ramhtml' in mosaic.
And the reason for this must to be the harcoded id (''rawhtml') in the code (see above).

**Comment by vangheem** [comment]
Okay, I see.

**Comment by vangheem** [comment]
This problem should be fixed with: https://github.com/plone/plone.app.mosaic/commit/af976c034711c5c77ba429add883939558448f56

**Comment by webmaxttor** [comment]
I made a test with mosaic-2.0.0rc2 and still the same problem.

**Comment by rristow** [comment]
Tested with mosaic-2.0.0rc2, still the same problem.
@vangheem - Can you reopen it?

**Comment by vangheem** [comment]
Maybe you need to edit/save resource registries to force re-merging bundles? I'm not sure if that is automatic on an upgrade.

Otherwise, can you explain how you're doing it or what the fix would be because it should work now. The tile name is not hard-coded.

**Comment by tomgross** [comment]
I can confirm this works.

**Comment by rristow** [comment]
It works now.
