### ISSUE TITLE
When selecting a mosaic layout, also show layouts description from manifest.cfg

### ISSUE THREAD

**Issue by AnneGilles** [plone/plone.app.mosaic#306]
The view/overlay/modal that lets users choose from the set of given layouts should, apart from displaying the *title* and *screenshot* for all given layouts, also display the *description* from manifest.cfg. This would improve usability for users, given the descriptions help them to decide which layout to choose.

**Comment by AnneGilles** [comment]
To achieve this, just one thing needs to be changed. 

In _src/plone/app/mosaic/browser/static/plone-mosaic.js_
replace 
`<p><%- layout.title %></p><img src="<%- portal_url %>/<%- screenshot %>">`
with
`<p><%- layout.title %></p><p><%- layout.description %></p><img src="<%- portal_url %>/<%- screenshot %>">`
and maybe add some styling/CSS.

**Comment by gforcada** [comment]
@AnneGilles would you mind creating a pull request for that? :-)

**Comment by AnneGilles** [comment]
@gforcada PR exists in #309

**Comment by datakurre** [comment]
I assume this was fixed with #309

**Comment by AnneGilles** [comment]
No, sorry, I'm afraid it was not fixed for good. The change must have been lost when the bundle was built.

There is no occurrence of "layout.description" in https://github.com/plone/plone.app.mosaic/blob/master/src/plone/app/mosaic/browser/static/plone-mosaic.js

**Comment by datakurre** [comment]
@AnneGilles I see. Your pull only included built bundles and not the original files. Please, could you provide new pull with only changes in sources static/js/ static/css/ -folders. Updated bundles are not necessary. It's enough that we update those for releases.

**Comment by datakurre** [comment]
@AnneGilles I'm sorry for not properly reviewing the original pull. Your should not add your changes to plone-mosaic.js or plone-mosaic.css, but for the original files from which those are built.

**Comment by AnneGilles** [comment]
see #325 and thanks!
