### ISSUE TITLE
mosaic CSS bundle only for logged users?

### ISSUE THREAD

**Issue by rafaeltcc** [plone/plone.app.mosaic#340]
Hi, I am using Plone 5.0.6, latest mosaic. I noticed that whenever I logged off, my frontpage edit with mosaic would get messy. I found out that rules from mosaic.css where myssing. In resource registry I found that mosaic.css bundle had a conditional rule: python: member is not None . Is this the correct behaviour? Why would I want a mosaic to be viewed desconfigured for anonymous users?

Thanks,

Rafael

**Comment by datakurre** [comment]
mosaic.css bundle contains mostly css for MosaicEditor; there should be another bundle called mosaic-grid to be registered also for anonymous user (as part of default bundle), and that should fix the layout for anonymous user; I'm curious, why that does not happen in your case :/

**Comment by rafaeltcc** [comment]
I will investigate.  Maybe was an interaction with another product I
installed collective.lazysizes.  I uninstalled it but the problem still
happens.  Maybe it messed something.

I also customized summary_view tile to have preview size images instead of
thumbnails,  but I doubt this broke it.

Thanks for the clarification. When I find out I will come back to tell.

Rafael

Em sexta-feira, 27 de janeiro de 2017, Asko Soukka <notifications@github.com>
escreveu:

**Comment by rafaeltcc** [comment]
In a just created Plone site (using my production installation), I see that, in the resource registry panel, I don't have the option to build the mosaic-grid bundle. Is this the normal behaviour? Or is something missing from my install? Maybe it is corrupted?

**Comment by rafaeltcc** [comment]
I investigated but can't find out why this is happening. I found this lines on my log.

2017-02-04 22:38:04 INFO plone.app.theming.policy local cache invalidated on thread 140120416966400
2017-02-04 22:38:04 INFO plone.app.theming.policy initializing local cache on thread 140120416966400 f

But my cache is off.

Although mosaic-grid is in the resource registry it does not get compiled...

Can anyone reproduce this? This is on a new install, with my custom product in buildout, but not installed in control panel.

**Comment by rafaeltcc** [comment]
I foud that in my http://localhost:8080/jornal/++plone++mosaic/mosaic-grid.css it is missing some clear css properties. There is no clear at all in this file, what I find very strange.

In http://localhost:8080/jornal/++plone++mosaic/plone-mosaic.css, displayed only to logged in users, I can found:

.mosaic-enabled .mosaic-grid-row:after,
.mosaic-enabled .mosaic-grid-row:after,
.mosaic-grid .mosaic-grid-row:after,
.mosaic-grid .mosaic-grid-row:after,
.template-layout .mosaic-grid-row:after,
.template-layout .mosaic-grid-row:after {
  clear: both;
}

This seems to be missing for not logged users to see the grid properly.

**Comment by vangheem** [comment]
> 2017-02-04 22:38:04 INFO plone.app.theming.policy local cache invalidated on thread 140120416966400
> 2017-02-04 22:38:04 INFO plone.app.theming.policy initializing local cache on thread 140120416966400 f


Is unrelated, normal.

`mosaic-grid` bundle should be getting merged into default.css

Seems to me that maybe https://github.com/plone/plone.app.mosaic/blob/master/src/plone/app/mosaic/browser/static/mosaic-grid.css is missing some necessary styles for basic grid implementation.

**Comment by rafaeltcc** [comment]
Can anyone try to reproduce it?

I took a look mosaic-grid.css and it really seems to be missing some importante properties, such as clear , display:table, and others, that seem to be causing my grid disconfiguration.

On the other hand, I see mosaic-grid is as it is for a long time, so I doubt something like that would have passed unoticed...

**Comment by michaeldunstan** [comment]
Yeah - I see the same problem here using 2.0.0rc4. Parts of the grid layout is missing for logged out users.

Images in rich text tiles are unexpectedly overlapping with other tiles. Probably because missing CSS for `.mosaic-tile img`

Also missing from the mosaic-grid bundle is CSS for the tile and row formats. Such as `mosaic-grid-row-dark` and `mosaic-tile-padding-right`.

**Comment by datakurre** [comment]
Would you be able to reproduce this with clean Plone installation and provide the steps?

**Comment by michaeldunstan** [comment]
I used http://plonemosaic200rc4.herokuapp.com to recreate the problem.

- Login to Plone.
- Create a new page.
- Set the page display to Mosaic layout.
- Edit the page.
- Enable custom layout for the page.
- Drag out a rich text field to create a new row. Set row format to "Dark background".
- Drag out a rich text field to create another new row. Edit the text so it just includes one large image. In this case 982 pixels wide.
- Drag out a rich text field to create a second column in the last row.
- Publish the page.
- Logout.
- Test the responsive layout of the page by squishing the browser window width around.

The first text field should have a dark background. And the large image should never overlap with the neighbouring text.

Here are the results I get. When logged in:

![grid__issue__340__ _site](https://cloud.githubusercontent.com/assets/360401/23628299/bb4caee0-0318-11e7-8eb0-81e69762e8ce.png)

And when logged out:

![grid__issue__340__ _site](https://cloud.githubusercontent.com/assets/360401/23628236/92533c8e-0318-11e7-9782-4ba7ebe6da8a.png)

**Comment by datakurre** [comment]
@agitator Would you be able to look this one more time?

**Comment by datakurre** [comment]
Just saw a related issue on the latest Plone 5.0.x where grid was completely missing outside editor, because body class was missing ``template-layout`` and that might have been fixed only for Plone 5.1. (That body.template-layout-prefix in mosaic-grid is probably unnecessary, because mosaic grid uses unique class names anyway.)

So possible fixes would be

* remove body.template-layout requirement from mosaic-grid.css
* move styles for issues reported in https://github.com/plone/plone.app.mosaic/issues/340#issuecomment-284523448 into mosaic-grid.css

**Comment by agitator** [comment]
looking into it

**Comment by agitator** [comment]
The "missing styles" for the basic grid seem to be loaded correctly from the default bundle - the columns collapse just rather early (<992px)

I can confirm the styles from mosaic.tiles.less because they are packed with the editor pattern and not available to anon users

I'd suggest 
- moving the styles from mosaic.tile.less to mosaic.styles.less
- register those styles as mosaic-styles bundle and merge it with the default bundle

Bonus: I haven't had any problems with ```template-layout``` but removing it seems fine

**Comment by datakurre** [comment]
This should now been fixed in 2.0rc5 (please, note the removal of third digit when compared to 2.0.0rc4).

http://ploneappmosaic20rc5.herokuapp.com/Plone/
